add mount safe for gchroot

diff --git a/docker/gchroot b/docker/gchroot
--- a/docker/gchroot
+++ b/docker/gchroot
@@ -64,6 +64,47 @@ complete_mount_point()
     echo "$mntpnt"
 }
 
+function mount_safe {
+  MOUNT_POINT=$1
+  MOUNT_DIR=$2
+
+  echo  $MOUNT_POINT
+  mkdir -p $MOUNT_POINT
+  if find $MOUNT_POINT -maxdepth 0 -empty | read v; then
+    mount --bind $MOUNT_DIR $MOUNT_POINT
+    MOUNT_READY=0
+    MOUNT_TRY=0
+    MAX_MOUNT_TRY=1000
+
+    if [ $# -eq 3 ]; then
+      MOUNT_FILE=$3
+      while [ ${MOUNT_READY} -eq 0 ]; do
+        if mountpoint -q ${MOUNT_POINT} && [ -e ${MOUNT_POINT}/${MOUNT_FILE} ]; then
+          MOUNT_READY=1
+        else
+          sleep 0.2
+          let MOUNT_TRY++
+          if [ $MOUNT_TRY -eq $MAX_MOUNT_TRY ]; then
+            MOUNT_READY=1
+          fi  
+        fi
+      done
+    else
+      while [ ${MOUNT_READY} -eq 0 ]; do
+        if mountpoint -q ${MOUNT_POINT}; then
+          MOUNT_READY=1
+        else
+          sleep 0.20
+          let MOUNT_TRY++
+          if [ $MOUNT_TRY -eq $MAX_MOUNT_TRY ]; then
+            MOUNT_READY=1
+          fi
+        fi
+      done  
+    fi
+  fi
+}
+
 cmd_attach ()
 {
     if [ "$#" -ne 1 ]; then
@@ -87,24 +128,58 @@ cmd_attach ()
     fi
     
     if [ -d "$imgpath" ]; then
-	rp=$(realpath $imgpath)
-	ln -s $rp $mntpnt
+        rp=$(realpath $imgpath)
+        ln -s $rp $mntpnt
     elif [ -f "$imgpath" ]; then
-	mkdir -p $mntpnt
-	mount -o loop $imgpath $mntpnt
+        mkdir -p $mntpnt
+        mount -o loop $imgpath $mntpnt
+    
+        MOUNT_READY=0
+        MOUNT_TRY=0
+        MAX_MOUNT_TRY=1000
+        while [ ${MOUNT_READY} -eq 0 ]; do
+          if mountpoint -q ${mntpnt} && [ -e ${mntpnt}/usr/local/share/gadgetron/gadgetron.xml ]; then
+              MOUNT_READY=1
+          else
+              sleep 0.2
+              let MOUNT_TRY++
+              if [ $MOUNT_TRY -eq $MAX_MOUNT_TRY ]; then
+                    MOUNT_READY=1
+                    echo "Mount failed for too many $MOUNT_TRY tries, ${imgpath} to ${mntpnt}"
+                    return 1
+              fi
+          fi
+        done
     else
-	return 1
+        return 1
     fi
 
     #Set global mount point variable
     MOUNTPOINT=$mntpnt
 
-    mkdir -p ${MOUNTPOINT}/proc
-    mkdir -p ${MOUNTPOINT}/sys
-    mkdir -p ${MOUNTPOINT}/dev
-    mount --bind /proc ${MOUNTPOINT}/proc 
-    mount --bind /sys  ${MOUNTPOINT}/sys
-    mount --bind /dev  ${MOUNTPOINT}/dev
+    if mountpoint -q ${MOUNTPOINT}; then
+        if ! mountpoint -q ${MOUNTPOINT}/proc; then
+            mount_safe "${MOUNTPOINT}/proc" /proc self/exe
+        fi
+
+        if ! mountpoint -q ${MOUNTPOINT}/dev; then
+            mount_safe "${MOUNTPOINT}/dev" /dev null
+        fi
+
+        if ! mountpoint -q ${MOUNTPOINT}/sys; then
+            mount_safe "${MOUNTPOINT}/sys" /sys kernel
+        fi
+    else
+        echo "${MOUNTPOINT} is not a valid mounting point ... "
+        return 1
+    fi
+
+    #mkdir -p ${MOUNTPOINT}/proc
+    #mkdir -p ${MOUNTPOINT}/sys
+    #mkdir -p ${MOUNTPOINT}/dev
+    #mount --bind /proc ${MOUNTPOINT}/proc 
+    #mount --bind /sys  ${MOUNTPOINT}/sys
+    #mount --bind /dev  ${MOUNTPOINT}/dev
 
     for i in "${BINDVOLUMES[@]}"
     do
